SET(CMAKE_MAKE_PROGRAM "$ENV{MAKE}" CACHE STRING "" FORCE)
SET(CMAKE_C_COMPILER "$ENV{CC}" CACHE STRING "" FORCE)
SET(CMAKE_CXX_COMPILER "$ENV{CXX}" CACHE STRING "" FORCE)
SET(CMAKE_USE_OPENSSL FALSE CACHE BOOL "" FORCE)
